DATASET:
  BEHAVIOR:
    final_file_path: final.xlsx
    midterm_file_path: midterm.xlsx
    social_network_file_path: Social_network_V2.xlsx
  EEG:
    preload: False
    check_data: auto #auto or manually set a list of subj id


PROCESSING:
  PREPROCESSING:
    DO: True
    SAVE_PATH: /data/xiaowei/social_network/HENU/preprocessing
    FILTER:
      DO: True
      hp: 1
      lp: 40
    ICA:
      
    
