GLOBAL:
  seed: &seed 42
  n_jobs: &n_jobs -1
  o_sfreqs: &o_sfreq 500
DATASET:
  BEHAVIOR:
    final_file_path: final.xlsx
    midterm_file_path: midterm.xlsx
    social_network_file_path: Social_network_V2.xlsx
  EEG:
    preload: False
    check_data: auto #auto or manually set a list of subj id


PROCESSING:
  PREPROCESSING:
    DO: False
    SAVE_PATH: &EPOCH_PATH /data/xiaowei/social_network/HENU/preprocessing
    n_jobs: -1
    CHANNEL:
      montageName: /data/xiaowei/social_network/HENU/data/standard-10-5-cap385.elp
      channelTypes: {}
      dropChannel: [IO,]
      mapping: {}
    CROP:
      DO: True
      tmin: 30
      tmax: 330
    RESAMPLE:
      DO: False
      sfreq: 500
    FILTER:
      DO: True
      hp: &hp 1
      lp: &lp 40
    NOTCH_FILTER:
      DO: False
      freq: 50
    EPOCH:
      DurationTime: 2
      MarkName: &event_name T
    ICA:
      DO: True
      seed: *seed
    REJECT:
      DO: True
  FEATURE_EXTRACTION:
    EPOCH_PATH: *EPOCH_PATH
    SAVE_PATH: &FEATURE_PATH /data/xiaowei/social_network/HENU/EEG_features
    PSD:
      DO: True
      fmin: *hp
      fmax: *lp
      n_jobs: *n_jobs
    FUNCTIONALCONNECTIVITY:
      DO: True
      method: [coh, cohy, imcoh, plv, ciplv, ppc, pli, wpli, wpli2_debiased]
      sfreq: *o_sfreq
      fmin: *hp
      fmax: *lp
      faverage: True
      n_jobs: *n_jobs
      
  SOCIAL_NETWORK:
    DO: True
    SAVE_PATH: /data/xiaowei/social_network/HENU/EEG_SN
    FEATURE: {'PSD': *FEATURE_PATH}
    EPOCH_PATH: *EPOCH_PATH 


      
  BEHAVIOR:


      
    
