GLOBAL:
  seed: &seed 42
  n_jobs: &n_jobs -1
  o_sfreqs: &o_sfreq 500
DATASET:
  SURVEY:
    final_file_path: final.xlsx
    midterm_file_path: midterm.xlsx
    social_network_file_path: Social_network_V2.xlsx
  EEG:
    preload: False
    check_data: auto #auto or manually set a list of subj id


PROCESSING:
  PREPROCESSING:
    DO: False
    SAVE_PATH: &EPOCH_PATH /data/xiaowei/social_network/HENU/preprocessing
    n_jobs: *n_jobs
    CHANNEL:
      montageName: /data/xiaowei/social_network/HENU/data/standard-10-5-cap385.elp
      channelTypes: {}
      dropChannel: [IO,]
      mapping: {}
    CROP:
      DO: True
      tmin: 30
      tmax: 330
    RESAMPLE:
      DO: False
      sfreq: 500
    FILTER:
      DO: True
      hp: &hp 1
      lp: &lp 40
    NOTCH_FILTER:
      DO: False
      freq: 50
    REREFERENCE:
      DO: True
      ref_channels: 'average' # a list of channel names, or average 
    EPOCH:
      DurationTime: 2
      MarkName: &event_name T
    ICA:
      DO: True
      seed: *seed
    REJECT:
      DO: True
  FEATURE_EXTRACTION:
    EPOCH_PATH: *EPOCH_PATH
    SAVE_PATH: &FEATURE_PATH /data/xiaowei/social_network/HENU/EEG_features
    PSD: &PSD
      DO: True
      fmin: *hp
      fmax: *lp
      n_jobs: *n_jobs
    FUNCTIONALCONNECTIVITY: &FUNCTIONALCONNECTIVITY
      DO: True
      method: [coh, cohy, imcoh, plv, ciplv, ppc, pli, wpli, wpli2_debiased]
      sfreq: *o_sfreq
      fmin: *hp
      fmax: *lp
      faverage: True
      n_jobs: *n_jobs
      
  EEG_SOCIAL_NETWORK:
    DO: False
    SAVE_PATH: /data/xiaowei/social_network/HENU/EEG_SN
    FEATURE: {'PSD': *FEATURE_PATH}
    EPOCH_PATH: *EPOCH_PATH 
    VISUALIZATION: True

  # TODO: add the following processing steps
  SURVEY_SOCIAL_NETWORK:
    DO: False
    SAVE_PATH: /data/xiaowei/social_network/HENU/survey_SN
    EPOCH_PATH: *EPOCH_PATH 
    VISUALIZATION: True
  


REGRESSION:
  EEG_OVO:
    DO: True
    SAVE_PATH: /data/xiaowei/social_network/HENU/EEG_regression
    EEG_FEATURE: {'PSD': *PSD, 'FUNCTIONALCONNECTIVITY': *FUNCTIONALCONNECTIVITY}
    EEG_FEATURE_PATH: *FEATURE_PATH
    
    # MODEL:
    #   model_type: LinearRegression
    #   standardize: True
    #   test_rate: 0.2
    #   split_random_state: *seed
    #   kwargs: {n_jobs: *n_jobs}
    #   VISUALIZATION: True

    # MODEL:
    #   model_type: Ridge
    #   standardize: True
    #   test_rate: 0.2
    #   split_random_state: *seed
    #   kwargs: {random_state: *seed}
    #   VISUALIZATION: True

    # MODEL:
    #   model_type: svm.SVR
    #   standardize: True
    #   test_rate: 0.2
    #   split_random_state: *seed
    #   kwargs: {kernel: rbf,cache_size: 1000}
    #   VISUALIZATION: True
    MODEL:
      model_type: XGBRegressor
      standardize: True
      test_rate: 0.2
      split_random_state: *seed
      kwargs: {verbosity: 0, objective: reg:squarederror}
      VISUALIZATION: True
    
  

    


      
    
